# Соответствие цветов пользователей Discord в Minecraft
# Цвета автоматически назначаются при первом сообщении пользователя
# Формат: Discord User ID -> HEX-код цвета

user-colors:
# Пример:
# "123456789012345678": "#FF5555"
# "987654321098765432": "#55FF55"
